#!/bin/bash -e

$_CMAKE \
	-DFT_DISABLE_ZLIB=ON \
	-DFT_DISABLE_BZIP2=ON \
	-DFT_DISABLE_PNG=ON \
	-DFT_DISABLE_HARFBUZZ=ON \
	-DFT_DISABLE_BROTLI=ON

NDK_WRAPPER_APPEND=-Oz $_NINJA
DESTDIR="$prefix_dir" $_NINJA install
