#!/bin/bash -e
: "${TARGET_PREFIX_DIR:?TARGET_PREFIX_DIR is not set}"

$_CMAKE \
	-DFT_DISABLE_ZLIB=ON \
	-DFT_DISABLE_BZIP2=ON \
	-DFT_DISABLE_PNG=ON \
	-DFT_DISABLE_HARFBUZZ=ON \
	-DFT_DISABLE_BROTLI=ON

$_NINJA
DESTDIR="$TARGET_PREFIX_DIR" $_NINJA install
