#!/bin/bash -e
: "${TARGET_PREFIX_DIR:?TARGET_PREFIX_DIR is not set}"

cat >include/mbedtls/mbedtls_config.h <<"END"
#define MBEDTLS_HAVE_ASM
#define MBEDTLS_DEPRECATED_REMOVED
#define MBEDTLS_AES_USE_HARDWARE_ONLY
// #define MBEDTLS_ECP_DP_SECP256R1_ENABLED
#define MBEDTLS_ECP_DP_CURVE25519_ENABLED
// #define MBEDTLS_ECP_NIST_OPTIM
#define MBEDTLS_FS_IO
#define MBEDTLS_PKCS1_V21
#define MBEDTLS_SSL_KEEP_PEER_CERTIFICATE
#define MBEDTLS_SSL_PROTO_TLS1_3
#define MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_EPHEMERAL_ENABLED
#define MBEDTLS_SSL_SERVER_NAME_INDICATION
#define MBEDTLS_THREADING_PTHREAD
#define MBEDTLS_X509_RSASSA_PSS_SUPPORT
#define MBEDTLS_AESCE_C
#define MBEDTLS_AES_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_BASE64_C
#define MBEDTLS_BIGNUM_C
#define MBEDTLS_CIPHER_C
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_ECDH_C
// #define MBEDTLS_ECDSA_C
#define MBEDTLS_ECP_C
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_GCM_C
#define MBEDTLS_GCM_LARGE_TABLE
#define MBEDTLS_HKDF_C
#define MBEDTLS_MD_C
#define MBEDTLS_NET_C
#define MBEDTLS_OID_C
#define MBEDTLS_PK_C
#define MBEDTLS_PK_PARSE_C
#define MBEDTLS_PSA_CRYPTO_C
#define MBEDTLS_RSA_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_SHA256_USE_ARMV8_A_CRYPTO_ONLY
#define MBEDTLS_SSL_CLI_C
#define MBEDTLS_SSL_TLS_C
#define MBEDTLS_THREADING_C
#define MBEDTLS_X509_USE_C
#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_MPI_WINDOW_SIZE 6
// #define MBEDTLS_ECP_WINDOW_SIZE 7
END

NDK_WRAPPER_DISABLED=1 $_CMAKE \
	-DENABLE_PROGRAMS=OFF \
	-DENABLE_TESTING=OFF

$_NINJA
$_NINJA install
