#!/bin/bash -e
: "${TARGET_PREFIX_DIR:?TARGET_PREFIX_DIR is not set}"

cat >include/mbedtls/mbedtls_config.h <<END
#define MBEDTLS_DEPRECATED_REMOVED

#define MBEDTLS_HAVE_ASM
#define MBEDTLS_AESCE_C
#define MBEDTLS_AES_USE_HARDWARE_ONLY
#define MBEDTLS_SHA256_USE_ARMV8_A_CRYPTO_ONLY
#define MBEDTLS_MPI_WINDOW_SIZE 6

// #define MBEDTLS_THREADING_C
// #define MBEDTLS_THREADING_PTHREAD

#define MBEDTLS_SSL_CLI_C
#define MBEDTLS_SSL_TLS_C
#define MBEDTLS_SSL_PROTO_TLS1_3
#define MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_EPHEMERAL_ENABLED
#define MBEDTLS_SSL_KEEP_PEER_CERTIFICATE
#define MBEDTLS_SSL_SERVER_NAME_INDICATION

#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_ENTROPY_C

#define MBEDTLS_PK_C
#define MBEDTLS_PK_PARSE_C
#define MBEDTLS_X509_USE_C
#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_X509_RSASSA_PSS_SUPPORT
#define MBEDTLS_X509_REMOVE_INFO

#define MBEDTLS_FS_IO

#define MBEDTLS_PSA_CRYPTO_C
#define MBEDTLS_USE_PSA_CRYPTO
#define MBEDTLS_PSA_CRYPTO_CONFIG
#define MBEDTLS_PSA_ASSUME_EXCLUSIVE_BUFFERS
END

cat >include/psa/crypto_config.h <<END
#ifndef PSA_CRYPTO_CONFIG_H
#define PSA_CRYPTO_CONFIG_H

#define PSA_WANT_ALG_HKDF_EXTRACT 1
#define PSA_WANT_ALG_HKDF_EXPAND 1
#define PSA_WANT_ALG_ECDH 1
#define PSA_WANT_ECC_MONTGOMERY_255 1
#define PSA_WANT_KEY_TYPE_AES 1
#define PSA_WANT_ALG_GCM 1
#define PSA_WANT_ALG_SHA_256 1
#define PSA_WANT_ALG_RSA_PSS 1
#define PSA_WANT_KEY_TYPE_RSA_PUBLIC_KEY 1
#define PSA_WANT_KEY_TYPE_ECC_KEY_PAIR_GENERATE 1

#endif
END

NDK_WRAPPER_DISABLED=1 $_CMAKE \
	-DENABLE_PROGRAMS=OFF \
	-DENABLE_TESTING=OFF

$_NINJA
$_NINJA install
